import type { Metadata } from 'next';

export const metadata: Metadata = { "title": "Privacy & cookies · Cosmetic Science Lab", "description": "How Cosmetic Science Lab collects, uses and protects enquiry data, and how cookies and analytics are used on this site.", "keywords": "Privacy, cookies, cosmetic product development, Cosmetic Science Lab", "authors": [{ "name": "Cosmetic Science Lab" }], "robots": "noindex, nofollow", "alternates": { "canonical": "https://www.cosmeticsciencelab.com/privacy", "languages": { "en": "https://www.cosmeticsciencelab.com/privacy", "x-default": "https://www.cosmeticsciencelab.com/privacy" } }, "openGraph": { "type": "website", "siteName": "Cosmetic Science Lab", "title": "Privacy & cookies · Cosmetic Science Lab", "description": "How Cosmetic Science Lab collects, uses and protects enquiry data, and how cookies and analytics are used on this site.", "url": "https://www.cosmeticsciencelab.com/privacy", "locale": "en_GB", "images": [{ "url": "https://www.cosmeticsciencelab.com/images/og-image.png", "width": 1200, "height": 630 }] }, "twitter": { "card": "summary_large_image", "title": "Privacy & cookies · Cosmetic Science Lab", "description": "How Cosmetic Science Lab collects, uses and protects enquiry data, and how cookies and analytics are used on this site.", "images": ["https://www.cosmeticsciencelab.com/images/og-image.png"] } };

export default function Page() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: "{\"@context\": \"https://schema.org\", \"@graph\": [{\"@type\": \"Organization\", \"@id\": \"https://www.cosmeticsciencelab.com/#org\", \"name\": \"Cosmetic Science Lab\", \"url\": \"https://www.cosmeticsciencelab.com/\", \"logo\": \"https://www.cosmeticsciencelab.com/images/logo.png\", \"parentOrganization\": {\"@type\": \"Organization\", \"name\": \"Guires Group\"}, \"sameAs\": [\"https://www.foodresearchlab.com/\"], \"email\": \"info@cosmeticsciencelab.com\", \"identifier\": {\"@type\": \"PropertyValue\", \"propertyID\": \"CIN\", \"value\": \"U74900TN2011PTC083063\"}, \"hasCredential\": {\"@type\": \"EducationalOccupationalCredential\", \"credentialCategory\": \"ISO 9001 certificate\", \"identifier\": \"H3CR9TCU20251212INDQM10N\"}, \"address\": [{\"@type\": \"PostalAddress\", \"streetAddress\": \"MIIC Unit 52-56, Greenheys Business Centre, Pencroft Way\", \"addressLocality\": \"Manchester\", \"postalCode\": \"M15 6JJ\", \"addressCountry\": \"GB\"}, {\"@type\": \"PostalAddress\", \"streetAddress\": \"7408 Dominion Park Ln, #1108\", \"addressLocality\": \"Charlotte\", \"addressRegion\": \"NC\", \"addressCountry\": \"US\"}, {\"@type\": \"PostalAddress\", \"streetAddress\": \"55-E (NP), Industrial Estate, Ambattur\", \"addressLocality\": \"Chennai\", \"postalCode\": \"600098\", \"addressCountry\": \"IN\"}], \"contactPoint\": [{\"@type\": \"ContactPoint\", \"contactType\": \"sales\", \"telephone\": \"+44-161-394-1144\", \"areaServed\": \"GB\"}, {\"@type\": \"ContactPoint\", \"contactType\": \"sales\", \"telephone\": \"+1-972-502-9262\", \"areaServed\": \"US\"}, {\"@type\": \"ContactPoint\", \"contactType\": \"sales\", \"telephone\": \"+91-95662-99022\", \"areaServed\": \"IN\"}]}, {\"@type\": \"WebPage\", \"@id\": \"https://www.cosmeticsciencelab.com/privacy\", \"url\": \"https://www.cosmeticsciencelab.com/privacy\", \"name\": \"Privacy & cookies · Cosmetic Science Lab\", \"description\": \"How Cosmetic Science Lab collects, uses and protects enquiry data, and how cookies and analytics are used on this site.\", \"isPartOf\": {\"@type\": \"WebSite\", \"name\": \"Cosmetic Science Lab\", \"url\": \"https://www.cosmeticsciencelab.com/\"}, \"publisher\": {\"@id\": \"https://www.cosmeticsciencelab.com/#org\"}}, {\"@type\": \"BreadcrumbList\", \"itemListElement\": [{\"@type\": \"ListItem\", \"position\": 1, \"name\": \"Home\", \"item\": \"https://www.cosmeticsciencelab.com/\"}, {\"@type\": \"ListItem\", \"position\": 2, \"name\": \"Privacy & cookies\", \"item\": \"https://www.cosmeticsciencelab.com/privacy\"}]}]}" }} />
      <><header className={"page-hero"}><div className={"wrap"} style={{"gridTemplateColumns": "1fr"}}><div><nav className={"crumbs"} aria-label={"Breadcrumb"}><a href={"/"}>{"Home"}</a><span>{"/"}</span><span>{"Privacy & cookies"}</span></nav><h1>{"Privacy & cookies"}</h1><p className={"lede"}>{"How Cosmetic Science Lab collects, uses and protects your information."}</p></div></div></header><section className={"block"}><div className={"wrap"}><p className={"note"} style={{"marginBottom": "28px"}}><b>{"Draft for legal review."}</b>{" Replace this text with your approved policy before launch."}</p><div className={"rows"}><div><h3>{"Who we are"}</h3><p>{"Cosmetic Science Lab, a Guires Group company (CIN U74900TN2011PTC083063). [Registered entity name and data-protection contact]."}</p></div><div><h3>{"What we collect"}</h3><p>{"The details you enter in our enquiry form (name, business email, phone, company, country and your message) and, if you accept analytics cookies, anonymous usage data."}</p></div><div><h3>{"Why we use it"}</h3><p>{"To respond to your enquiry, prepare proposals and, if you opt in, send regulatory and ingredient updates. Legal basis: legitimate interest and, for updates and analytics, consent."}</p></div><div><h3>{"Confidentiality"}</h3><p>{"Briefs and formulas you share are handled under NDA and never used for other clients."}</p></div><div><h3>{"Cookies"}</h3><p>{"Essential cookies run the site. Analytics cookies load only after you accept them in the cookie banner. You can change your choice by clearing this site’s cookies."}</p></div><div><h3>{"Your rights"}</h3><p>{"Access, correction, deletion and objection under GDPR and UK GDPR. Contact [privacy email]."}</p></div><div><h3>{"Retention"}</h3><p>{"Enquiry data kept for [period] unless a project starts."}</p></div></div></div></section></>
    </>
  );
}
