import type { Metadata } from 'next';

export const metadata: Metadata = { "title": "Page not found · Cosmetic Science Lab", "description": "The page you were looking for could not be found. Browse Cosmetic Science Lab services, markets and insights, or contact our team.", "keywords": "Page not found, cosmetic product development, Cosmetic Science Lab", "authors": [{ "name": "Cosmetic Science Lab" }], "robots": "noindex, nofollow", "alternates": { "canonical": "https://www.cosmeticsciencelab.com/404", "languages": { "en": "https://www.cosmeticsciencelab.com/404", "x-default": "https://www.cosmeticsciencelab.com/404" } }, "openGraph": { "type": "website", "siteName": "Cosmetic Science Lab", "title": "Page not found · Cosmetic Science Lab", "description": "The page you were looking for could not be found. Browse Cosmetic Science Lab services, markets and insights, or contact our team.", "url": "https://www.cosmeticsciencelab.com/404", "locale": "en_GB", "images": [{ "url": "https://www.cosmeticsciencelab.com/images/og-image.png", "width": 1200, "height": 630 }] }, "twitter": { "card": "summary_large_image", "title": "Page not found · Cosmetic Science Lab", "description": "The page you were looking for could not be found. Browse Cosmetic Science Lab services, markets and insights, or contact our team.", "images": ["https://www.cosmeticsciencelab.com/images/og-image.png"] } };

export default function NotFound() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: "{\"@context\": \"https://schema.org\", \"@graph\": [{\"@type\": \"Organization\", \"@id\": \"https://www.cosmeticsciencelab.com/#org\", \"name\": \"Cosmetic Science Lab\", \"url\": \"https://www.cosmeticsciencelab.com/\", \"logo\": \"https://www.cosmeticsciencelab.com/images/logo.png\", \"parentOrganization\": {\"@type\": \"Organization\", \"name\": \"Guires Group\"}, \"sameAs\": [\"https://www.foodresearchlab.com/\"], \"email\": \"info@cosmeticsciencelab.com\", \"identifier\": {\"@type\": \"PropertyValue\", \"propertyID\": \"CIN\", \"value\": \"U74900TN2011PTC083063\"}, \"hasCredential\": {\"@type\": \"EducationalOccupationalCredential\", \"credentialCategory\": \"ISO 9001 certificate\", \"identifier\": \"H3CR9TCU20251212INDQM10N\"}, \"address\": [{\"@type\": \"PostalAddress\", \"streetAddress\": \"MIIC Unit 52-56, Greenheys Business Centre, Pencroft Way\", \"addressLocality\": \"Manchester\", \"postalCode\": \"M15 6JJ\", \"addressCountry\": \"GB\"}, {\"@type\": \"PostalAddress\", \"streetAddress\": \"7408 Dominion Park Ln, #1108\", \"addressLocality\": \"Charlotte\", \"addressRegion\": \"NC\", \"addressCountry\": \"US\"}, {\"@type\": \"PostalAddress\", \"streetAddress\": \"55-E (NP), Industrial Estate, Ambattur\", \"addressLocality\": \"Chennai\", \"postalCode\": \"600098\", \"addressCountry\": \"IN\"}], \"contactPoint\": [{\"@type\": \"ContactPoint\", \"contactType\": \"sales\", \"telephone\": \"+44-161-394-1144\", \"areaServed\": \"GB\"}, {\"@type\": \"ContactPoint\", \"contactType\": \"sales\", \"telephone\": \"+1-972-502-9262\", \"areaServed\": \"US\"}, {\"@type\": \"ContactPoint\", \"contactType\": \"sales\", \"telephone\": \"+91-95662-99022\", \"areaServed\": \"IN\"}]}, {\"@type\": \"WebPage\", \"@id\": \"https://www.cosmeticsciencelab.com/404\", \"url\": \"https://www.cosmeticsciencelab.com/404\", \"name\": \"Page not found · Cosmetic Science Lab\", \"description\": \"The page you were looking for could not be found. Browse Cosmetic Science Lab services, markets and insights, or contact our team.\", \"isPartOf\": {\"@type\": \"WebSite\", \"name\": \"Cosmetic Science Lab\", \"url\": \"https://www.cosmeticsciencelab.com/\"}, \"publisher\": {\"@id\": \"https://www.cosmeticsciencelab.com/#org\"}}]}" }} />
      <header className={"page-hero"}><div className={"wrap"} style={{"gridTemplateColumns": "1fr"}}><div><p className={"eyebrow"}>{"Error 404"}</p><h1>{"This page "}<em>{"isn’t here."}</em></h1><p className={"lede"}>{"It may have moved when we launched the new site. Try one of these instead."}</p><div className={"hero-ctas"}><a className={"btn btn-dark"} href={"/"}>{"Home"}</a><a className={"btn btn-line"} href={"/formulation"}>{"Formulation"}</a><a className={"btn btn-line"} href={"/regulatory"}>{"Markets"}</a><a className={"btn btn-line"} href={"/contact"}>{"Contact"}</a></div></div></div></header>
    </>
  );
}
