import type { Metadata } from 'next';

export const metadata: Metadata = { "title": "Terms of use · Cosmetic Science Lab", "description": "The terms that apply when you use the Cosmetic Science Lab website, including intellectual property and limits of the information provided.", "keywords": "Terms of use, cosmetic product development, Cosmetic Science Lab", "authors": [{ "name": "Cosmetic Science Lab" }], "robots": "noindex, nofollow", "alternates": { "canonical": "https://www.cosmeticsciencelab.com/terms", "languages": { "en": "https://www.cosmeticsciencelab.com/terms", "x-default": "https://www.cosmeticsciencelab.com/terms" } }, "openGraph": { "type": "website", "siteName": "Cosmetic Science Lab", "title": "Terms of use · Cosmetic Science Lab", "description": "The terms that apply when you use the Cosmetic Science Lab website, including intellectual property and limits of the information provided.", "url": "https://www.cosmeticsciencelab.com/terms", "locale": "en_GB", "images": [{ "url": "https://www.cosmeticsciencelab.com/images/og-image.png", "width": 1200, "height": 630 }] }, "twitter": { "card": "summary_large_image", "title": "Terms of use · Cosmetic Science Lab", "description": "The terms that apply when you use the Cosmetic Science Lab website, including intellectual property and limits of the information provided.", "images": ["https://www.cosmeticsciencelab.com/images/og-image.png"] } };

export default function Page() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: "{\"@context\": \"https://schema.org\", \"@graph\": [{\"@type\": \"Organization\", \"@id\": \"https://www.cosmeticsciencelab.com/#org\", \"name\": \"Cosmetic Science Lab\", \"url\": \"https://www.cosmeticsciencelab.com/\", \"logo\": \"https://www.cosmeticsciencelab.com/images/logo.png\", \"parentOrganization\": {\"@type\": \"Organization\", \"name\": \"Guires Group\"}, \"sameAs\": [\"https://www.foodresearchlab.com/\"], \"email\": \"info@cosmeticsciencelab.com\", \"identifier\": {\"@type\": \"PropertyValue\", \"propertyID\": \"CIN\", \"value\": \"U74900TN2011PTC083063\"}, \"hasCredential\": {\"@type\": \"EducationalOccupationalCredential\", \"credentialCategory\": \"ISO 9001 certificate\", \"identifier\": \"H3CR9TCU20251212INDQM10N\"}, \"address\": [{\"@type\": \"PostalAddress\", \"streetAddress\": \"MIIC Unit 52-56, Greenheys Business Centre, Pencroft Way\", \"addressLocality\": \"Manchester\", \"postalCode\": \"M15 6JJ\", \"addressCountry\": \"GB\"}, {\"@type\": \"PostalAddress\", \"streetAddress\": \"7408 Dominion Park Ln, #1108\", \"addressLocality\": \"Charlotte\", \"addressRegion\": \"NC\", \"addressCountry\": \"US\"}, {\"@type\": \"PostalAddress\", \"streetAddress\": \"55-E (NP), Industrial Estate, Ambattur\", \"addressLocality\": \"Chennai\", \"postalCode\": \"600098\", \"addressCountry\": \"IN\"}], \"contactPoint\": [{\"@type\": \"ContactPoint\", \"contactType\": \"sales\", \"telephone\": \"+44-161-394-1144\", \"areaServed\": \"GB\"}, {\"@type\": \"ContactPoint\", \"contactType\": \"sales\", \"telephone\": \"+1-972-502-9262\", \"areaServed\": \"US\"}, {\"@type\": \"ContactPoint\", \"contactType\": \"sales\", \"telephone\": \"+91-95662-99022\", \"areaServed\": \"IN\"}]}, {\"@type\": \"WebPage\", \"@id\": \"https://www.cosmeticsciencelab.com/terms\", \"url\": \"https://www.cosmeticsciencelab.com/terms\", \"name\": \"Terms of use · Cosmetic Science Lab\", \"description\": \"The terms that apply when you use the Cosmetic Science Lab website, including intellectual property and limits of the information provided.\", \"isPartOf\": {\"@type\": \"WebSite\", \"name\": \"Cosmetic Science Lab\", \"url\": \"https://www.cosmeticsciencelab.com/\"}, \"publisher\": {\"@id\": \"https://www.cosmeticsciencelab.com/#org\"}}, {\"@type\": \"BreadcrumbList\", \"itemListElement\": [{\"@type\": \"ListItem\", \"position\": 1, \"name\": \"Home\", \"item\": \"https://www.cosmeticsciencelab.com/\"}, {\"@type\": \"ListItem\", \"position\": 2, \"name\": \"Terms of use\", \"item\": \"https://www.cosmeticsciencelab.com/terms\"}]}]}" }} />
      <><header className={"page-hero"}><div className={"wrap"} style={{"gridTemplateColumns": "1fr"}}><div><nav className={"crumbs"} aria-label={"Breadcrumb"}><a href={"/"}>{"Home"}</a><span>{"/"}</span><span>{"Terms of use"}</span></nav><h1>{"Terms of use"}</h1><p className={"lede"}>{"The terms that apply when you use this website."}</p></div></div></header><section className={"block"}><div className={"wrap"}><p className={"note"} style={{"marginBottom": "28px"}}><b>{"Draft for legal review."}</b>{" Replace this text with your approved policy before launch."}</p><div className={"rows"}><div><h3>{"Information only"}</h3><p>{"Content on this site is general information and not regulatory or legal advice for a specific product."}</p></div><div><h3>{"Intellectual property"}</h3><p>{"Site content belongs to Cosmetic Science Lab and Guires Group. Client formulas belong to clients, as set out in project agreements."}</p></div><div><h3>{"Links"}</h3><p>{"Links to other sites are provided for convenience; we are not responsible for their content."}</p></div><div><h3>{"Governing law"}</h3><p>{"[Jurisdiction]."}</p></div></div></div></section></>
    </>
  );
}
