import type { Metadata } from 'next';

export const metadata: Metadata = { "title": "Thank you · Cosmetic Science Lab", "description": "Thank you for contacting Cosmetic Science Lab. A scientist will reply to your enquiry within one working day with next steps.", "keywords": "Thank you, cosmetic product development, Cosmetic Science Lab", "authors": [{ "name": "Cosmetic Science Lab" }], "robots": "noindex, nofollow", "alternates": { "canonical": "https://www.cosmeticsciencelab.com/thank-you", "languages": { "en": "https://www.cosmeticsciencelab.com/thank-you", "x-default": "https://www.cosmeticsciencelab.com/thank-you" } }, "openGraph": { "type": "website", "siteName": "Cosmetic Science Lab", "title": "Thank you · Cosmetic Science Lab", "description": "Thank you for contacting Cosmetic Science Lab. A scientist will reply to your enquiry within one working day with next steps.", "url": "https://www.cosmeticsciencelab.com/thank-you", "locale": "en_GB", "images": [{ "url": "https://www.cosmeticsciencelab.com/images/og-image.png", "width": 1200, "height": 630 }] }, "twitter": { "card": "summary_large_image", "title": "Thank you · Cosmetic Science Lab", "description": "Thank you for contacting Cosmetic Science Lab. A scientist will reply to your enquiry within one working day with next steps.", "images": ["https://www.cosmeticsciencelab.com/images/og-image.png"] } };

export default function Page() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: "{\"@context\": \"https://schema.org\", \"@graph\": [{\"@type\": \"Organization\", \"@id\": \"https://www.cosmeticsciencelab.com/#org\", \"name\": \"Cosmetic Science Lab\", \"url\": \"https://www.cosmeticsciencelab.com/\", \"logo\": \"https://www.cosmeticsciencelab.com/images/logo.png\", \"parentOrganization\": {\"@type\": \"Organization\", \"name\": \"Guires Group\"}, \"sameAs\": [\"https://www.foodresearchlab.com/\"], \"email\": \"info@cosmeticsciencelab.com\", \"identifier\": {\"@type\": \"PropertyValue\", \"propertyID\": \"CIN\", \"value\": \"U74900TN2011PTC083063\"}, \"hasCredential\": {\"@type\": \"EducationalOccupationalCredential\", \"credentialCategory\": \"ISO 9001 certificate\", \"identifier\": \"H3CR9TCU20251212INDQM10N\"}, \"address\": [{\"@type\": \"PostalAddress\", \"streetAddress\": \"MIIC Unit 52-56, Greenheys Business Centre, Pencroft Way\", \"addressLocality\": \"Manchester\", \"postalCode\": \"M15 6JJ\", \"addressCountry\": \"GB\"}, {\"@type\": \"PostalAddress\", \"streetAddress\": \"7408 Dominion Park Ln, #1108\", \"addressLocality\": \"Charlotte\", \"addressRegion\": \"NC\", \"addressCountry\": \"US\"}, {\"@type\": \"PostalAddress\", \"streetAddress\": \"55-E (NP), Industrial Estate, Ambattur\", \"addressLocality\": \"Chennai\", \"postalCode\": \"600098\", \"addressCountry\": \"IN\"}], \"contactPoint\": [{\"@type\": \"ContactPoint\", \"contactType\": \"sales\", \"telephone\": \"+44-161-394-1144\", \"areaServed\": \"GB\"}, {\"@type\": \"ContactPoint\", \"contactType\": \"sales\", \"telephone\": \"+1-972-502-9262\", \"areaServed\": \"US\"}, {\"@type\": \"ContactPoint\", \"contactType\": \"sales\", \"telephone\": \"+91-95662-99022\", \"areaServed\": \"IN\"}]}, {\"@type\": \"WebPage\", \"@id\": \"https://www.cosmeticsciencelab.com/thank-you\", \"url\": \"https://www.cosmeticsciencelab.com/thank-you\", \"name\": \"Thank you · Cosmetic Science Lab\", \"description\": \"Thank you for contacting Cosmetic Science Lab. A scientist will reply to your enquiry within one working day with next steps.\", \"isPartOf\": {\"@type\": \"WebSite\", \"name\": \"Cosmetic Science Lab\", \"url\": \"https://www.cosmeticsciencelab.com/\"}, \"publisher\": {\"@id\": \"https://www.cosmeticsciencelab.com/#org\"}}]}" }} />
      <header className={"page-hero"}><div className={"wrap"} style={{"gridTemplateColumns": "1fr"}}><div><p className={"eyebrow"}>{"Enquiry received"}</p><h1>{"Thank you. "}<em>{"We’re on it."}</em></h1><p className={"lede"}>{"A scientist will read your brief and reply within one working day. If you asked for an NDA, it will come first."}</p><div className={"hero-ctas"}><a className={"btn btn-dark"} href={"/process"}>{"See how we work"}</a><a className={"btn btn-line"} href={"/insights"}>{"Read our insights"}</a></div></div></div></header>
    </>
  );
}
